### ISSUE TITLE
Hé Martijn, small issue

### ISSUE THREAD

**Issue by jorisroling** [martijndeh/check#1]
If I run this:

```
var check=require('type-check-system').default;
try {
    check('strValue',[String]);
} catch(e) {
    console.log(e)
}

```

I get:

```
{ [CheckError: Value "strValue" is not of type [null].]
  name: 'CheckError',
  key: null,
  message: 'Value "strValue" is not of type [null].' }
```

whereas I'd expect a message:
`'Value "strValue" is not of type [String].'`

BTW nice repo! 😉

**Comment by martijndeh** [comment]
Better late than never: this should be fixed. I consider this a breaking change so I bumped the release to 2.0.0 which should be available on npm as of now.
